# Generated by Django 6.0.4 on 2026-05-06 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_service_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimateDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='core.estimate')),
            ],
            options={
                'ordering': ['day_number'],
                'unique_together': {('estimate', 'day_number')},
            },
        ),
    ]
