# Generated by Django 6.0.4 on 2026-05-06 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_estimateday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimateitem',
            name='estimate',
        ),
        migrations.AddField(
            model_name='estimateitem',
            name='estimate_day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.estimateday'),
            preserve_default=False,
        ),
    ]
