# Generated by Django 6.0.4 on 2026-05-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_estimateitem_estimate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
