# Generated by Django 6.0.4 on 2026-05-11 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contractor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimateitem',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.service'),
        ),
    ]
