# Generated by Django 6.0.4 on 2026-05-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_estimateitem_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimateday',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='estimateday',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
