# Generated by Django 6.0.4 on 2026-05-11 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_estimateday_description_estimateday_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estimateday',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='estimateday',
            unique_together=set(),
        ),
    ]
