# Generated by Django 6.0.4 on 2026-05-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_estimateday_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
