# Generated by Django 6.0.4 on 2026-05-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_estimate_approved_at_estimate_is_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estimateday',
            options={'ordering': ['day_number']},
        ),
        migrations.AlterModelOptions(
            name='estimateitem',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='estimateday',
            constraint=models.UniqueConstraint(fields=('estimate', 'day_number'), name='unique_day_number_per_estimate'),
        ),
    ]
