# Generated by Django 6.0.4 on 2026-05-24 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_estimateday_options_alter_estimateitem_options_and_more'),
    ]

    operations = [
    ]
