# Generated by Django 6.0.4 on 2026-05-24 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20260524_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractor',
            name='category',
        ),
    ]
