# Generated by Django 6.0.4 on 2026-05-26 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_servicecategory_service_category_ref'),
    ]

    operations = [
    ]
