# Generated by Django 6.0.4 on 2026-05-26 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_service_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='category_ref',
            new_name='category',
        ),
    ]
