# Generated by Django 5.2.14 on 2026-06-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_contractor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('tagline', models.CharField(blank=True, max_length=255, verbose_name='Слоган')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('site', models.CharField(blank=True, max_length=255, verbose_name='Сайт')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Логотип')),
                ('manager_title', models.CharField(blank=True, default='Менеджер проекта', max_length=255, verbose_name='Должность подписанта')),
                ('manager_name', models.CharField(blank=True, max_length=255, verbose_name='Имя подписанта по умолчанию')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Профиль компании',
                'verbose_name_plural': 'Профиль компании',
            },
        ),
    ]
