# Generated by Django 5.2.14 on 2026-06-02 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_estimate_contract_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estimate',
            options={'ordering': ['-created_at', '-id']},
        ),
    ]
